POST http://localhost:5000/insertar_empleado
Content-Type: application/json

{
  "nombre": "Sofia Rodriguez", 
  "salario": 50000
}


### Consultar empleados

GET http://localhost:5000/listar_empleados



